### ISSUE TITLE
Update nokogiri dependency

### ISSUE THREAD

**Issue by marians** [giantswarm/talks-oponder-dockerizing-rails#1]
![image](https://user-images.githubusercontent.com/273727/35564617-05b7b682-05bb-11e8-8ec1-e0438132e1b3.png)

Ping @oponder

**Comment by oponder** [comment]
I think I'll just delete this repo.

**Comment by oponder** [comment]
@marians Any veto against that?

**Comment by marians** [comment]
No veto, do as you like
